#File containing all narrative text strings
messages = {"bridge":('You are now in the bridge', 'There is a paper clip and toothbrush and stapler'),
            "scene1":('You pressed the red button', 'The lights turn on'),
            "scene3":('You pressed the blue button','Unfortunately nothing happened. You stay until you die of thirst','Game Over'),
            "scene2":('You pressed the blue button', 'Congratulations...you suck', 'Game Over'),
            'game_intro': ('You have awoke inside of a room.', 'In it you see three buttons, one red, one blue and one green.', 'What do you do?', 'j: red k: blue l: green'),
            "scene4":("You picked up the paper clip","You stab yourself in the eye","You die"),
            "scene5":("You picked up the toothbrush","Why would you ever need a toothbrush you idiot","Game Over"),
            "scene6":("You picked up the stapler","Sadly it has no use to you because you are not Mcgyver","Game Over"),
            "halldo":("Well would you look at that it's a hallway", "There's three doors in front of you","Better hope there's something good in one of 'em"),
            "stordo":("You're now in storage","Looks like whoever lived here managed to pile up a whole lot of junk"),
            "cockdo":("It's the pilots bay", "There must be something useful in here"),
            "tank_intro": ("The wall slides open and what looks like the oxygen tank appears before you.","There sure is a lot of steam coming out of it","...that probably isn't good"),
            "obsdo":("Woah","The view in here is beautiful", "Oh look there's a telescope"),
            "commdo":("There sure are a lot of screens in here","Who even needs all of this?"),
            "unlock":("fuck u",""),
            "unlock2":("AWWWWWWWWWWWWWWWWWWWWWWWWWWWWW FUCCCCCCCCCCCKING HWWWWWWWWWWWWWLLLLLLLLLLLLL YEAHHHHHHHHHHHHHHHHHHHH"),
            "5":("75 percent left",""),
            "10":("50 percent left",""),
            "15":("25 percent left",""),
            "20":("0 percent left","")}
